import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { PageHeader } from "@/components/ui/PageHeader";

const Disclaimer = () => {
  return (
    <div className="min-h-screen flex flex-col bg-gray-50">
      <Header />

      <main className="flex-grow">
        <PageHeader
          title="Disclaimer"
          description="Important information about the limitations of our service"
        />

        <div className="container mx-auto px-4 py-8">
          <div className="bg-white p-8 rounded-lg shadow-sm">
            <div className="prose max-w-none">
              <p>Last Updated: November 15, 2023</p>

              <h2>Disclaimer</h2>
              <p>
                The information provided on ScamAdviser is for general
                informational purposes only. All information on the site is
                provided in good faith, however, we make no representation or
                warranty of any kind, express or implied, regarding the
                accuracy, adequacy, validity, reliability, availability, or
                completeness of any information on the site.
              </p>

              <h2>No Liability</h2>
              <p>
                Under no circumstance shall we have any liability to you for any
                loss or damage of any kind incurred as a result of the use of
                the site or reliance on any information provided on the site.
                Your use of the site and your reliance on any information on the
                site is solely at your own risk.
              </p>

              <h2>Accuracy of Information</h2>
              <p>
                ScamAdviser uses various technologies, algorithms, and data
                sources to assess the trustworthiness of websites, including
                domain registration information, website content analysis, and
                user reports. However, these assessments are probabilistic in
                nature and may not always be accurate.
              </p>
              <p>
                A website that receives a high trust score from our system may
                still engage in fraudulent activities, and conversely, a
                legitimate website may receive a low trust score due to various
                factors. Our assessments should be considered as one of many
                tools to help you make informed decisions, not as definitive
                statements of a website's legitimacy.
              </p>

              <h2>External Links</h2>
              <p>
                The site may contain links to external websites that are not
                provided or maintained by or in any way affiliated with us.
                Please note that we do not guarantee the accuracy, relevance,
                timeliness, or completeness of any information on these external
                websites.
              </p>

              <h2>Professional Advice</h2>
              <p>
                The information on ScamAdviser is not intended as and should not
                be taken as professional advice. If you suspect you have been a
                victim of a scam or fraud, we recommend contacting relevant
                authorities, such as your local police, consumer protection
                agencies, or legal professionals.
              </p>

              <h2>User-Generated Content</h2>
              <p>
                Our platform allows users to submit reports about websites and
                other entities they believe to be fraudulent. These reports
                represent the opinions of individual users and have not been
                verified by ScamAdviser. We do not endorse or take
                responsibility for the accuracy of user-generated content.
              </p>

              <h2>Changes and Errors</h2>
              <p>
                We reserve the right to change the information on the site
                without notice. We make reasonable efforts to provide accurate
                information, but errors may exist. If you identify an error or
                have concerns about our information, please contact us.
              </p>

              <h2>Business Listings</h2>
              <p>
                Businesses can claim and manage their listings on ScamAdviser.
                While we take steps to verify these claims, we cannot guarantee
                that all business information is accurate or that all claimed
                listings are managed by authorized representatives of those
                businesses.
              </p>

              <h2>Use of Our Trust Scores</h2>
              <p>
                Trust scores and other assessments generated by ScamAdviser are
                the property of ScamAdviser and may not be reproduced,
                distributed, or used for commercial purposes without our express
                written permission.
              </p>

              <h2>Limitation on Liability</h2>
              <p>
                To the maximum extent permitted by applicable law, ScamAdviser
                shall not be liable for any indirect, incidental, special,
                consequential, or punitive damages, or any loss of profits or
                revenues, whether incurred directly or indirectly, or any loss
                of data, use, goodwill, or other intangible losses, resulting
                from:
              </p>
              <ol>
                <li>Your use of or inability to use the site;</li>
                <li>
                  Any unauthorized access to or use of our servers and/or any
                  personal information stored therein;
                </li>
                <li>
                  Any interruption or cessation of transmission to or from the
                  site;
                </li>
                <li>
                  Any bugs, viruses, trojan horses, or the like that may be
                  transmitted to or through the site by any third party;
                </li>
                <li>
                  Any errors or omissions in any content or for any loss or
                  damage incurred as a result of the use of any content posted,
                  emailed, transmitted, or otherwise made available through the
                  site.
                </li>
              </ol>

              <h2>Contact Us</h2>
              <p>
                If you have any questions about this Disclaimer, please contact
                us:
              </p>
              <p>
                Email: legal@scamadviser.com
                <br />
                Postal Address: 123 Anti-Scam Street, Amsterdam, 1000 AB,
                Netherlands
              </p>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Disclaimer;
